Fix infinite reconcile loop
infrawatch/service-telemetry-operator pull request #445
Opened 2023-08-22 20:58 UTC by leifmadsen

Fix a potential infinite reconcile loop when deploying Grafana due to
updated hashing algorithm which changes the hash contents each time the
contents is hashed. Adds a fix which results in skipping the update of
the default-grafana-htpasswd Secret object to avoid the situation.

Also makes a small add to the when clause list for deploying
Elasticsearch so that only when it is enabled are the tasks included.

Closes: STF-1499
Signed-off-by: Leif Madsen <lmadsen@redhat.com>

2023-08-23 15:29 UTC, leifmadsen commented
I've done several tests now and I consider this ready for review.

The primary issue here was that when enabling hybrid mode in order to enable grafana, I was running into an infinite reconcile loop in STO due to the data in the default-grafana-htpasswd continually updating.

The changes here adds the same password hash in annotation to the secret, the same as how we do that for the deployment of grafana in order to allow restarting the grafana pod when the password is changed.

In this setup, I add a when clause to check that the annotation and annotation.hash-of-creds[...] is added for existing deployments (STF 1.5.2 and earlier), along with doing a secret update when the password hash changes (due to change of adminPassword in ServiceTelemetry CR), which happens just prior to the update of the deployment manifest for grafana so that the password is re-read by the grafana pod restart.

I am now able to flip between observabilityStrategy use_redhat and use_hybrid to extend the OBO deployment, and allowing for grafana to be deployed.

There are also a couple other efficiency changes added so that we're not creating secrets for elasticsearch when that is not enabled.

2023-08-23 15:31 UTC, leifmadsen commented on roles/servicetelemetry/vars/dummy_user_certs.yml
> +  -----END RSA PRIVATE KEY-----
this just fixes a local ansible-lint complaint about missing newline

2023-08-23 15:32 UTC, leifmadsen commented
test

2023-08-24 16:40 UTC, csibbitt requested changes
The code here looks okay, but I think it decreases security. Storing the password twice with two hashes increases the attack surface, and using a global salt for one of them somewhat weakens any hashes that share that global salt. I also think it could be simpler.

The root of the problem is that `password_hash("bcrypt")` uses a random salt (no second parameter), and the proposed solution is to store the creds a second time with a static salt by using `password_hash('sha256', (session_secret | b64encode)[:16] )` (note the second parameter). Then you use the now-static hash to detect changes. 

Simply using a static (not necesarrily global!) salt with bcrypt should solve the problem without extra gymnastics.

The best solution is to use a random salt when first generating the secret, but if the secret already exists, you reuse the existing salt (the 22 chars after the third $, see [3] Below) so that it's deterministic. That way we are still using a random, non-global salt, but each password's salt remains static through its lifetime, preventing the hash mutation and infinite loop problem.

[1] https://docs.ansible.com/ansible/latest/collections/ansible/builtin/password_lookup.html
[2] https://passlib.readthedocs.io/en/stable/lib/passlib.hash.bcrypt.html
[3] https://en.wikipedia.org/wiki/Bcrypt#Description

## Below
```
$ ansible localhost -m ansible.builtin.debug -a "msg=\"{{ 'test'| password_hash('bcrypt') }}\""
    "msg": "$2b$12$kFm89kOb8wJ.UzKHXk6PbOYNNA14Xwu2Jyd7RoT7rn4LN5eQq2Tam"
            \__/\/ \____________________/\_____________________________/
            Alg Cost      Salt                        Hash

# Random salt -> different string
$ ansible localhost -m ansible.builtin.debug -a "msg=\"{{ 'test'| password_hash('bcrypt') }}\""
    "msg": "$2b$12$OzXVBHsQlpeHX.dAPIeEm.xaIvVE9UjWvJI8RaItQfRI6vrj9hDbG"

# Original salt -> original string
$ ansible localhost -m ansible.builtin.debug -a "msg=\"{{ 'test'| password_hash('bcrypt', 'kFm89kOb8wJ.UzKHXk6PbO') }}\""
    "msg": "$2b$12$kFm89kOb8wJ.UzKHXk6PbOYNNA14Xwu2Jyd7RoT7rn4LN5eQq2Tam"
```

2023-08-24 20:23 UTC, leifmadsen commented
Read comments from Chris and talked with him out-of-band to come up with a proof that I can use to simplify everything. I'll remove the annotation from the secret, and can migrate from using the old hashing method to using bcrypt-based hashing everywhere rather than currently used sha256 for the grafana deployment (used for re-triggering deployment on password change).

```yaml
---
- name: k8s test
  hosts: localhost

  tasks:
  - name: Check for existing grafana htpasswd secret
    no_log: true
    k8s_info:
      api_version: v1
      kind: Secret
      namespace: service-telemetry
      name: 'default-grafana-htpasswd'
    register: grafana_htpasswd_secret

  - debug:
      var: grafana_htpasswd_secret.resources[0].data.auth | b64decode

  - set_fact:
      grafana_htpasswd_salt: "{{ (grafana_htpasswd_secret.resources[0].data.auth | b64decode | split('$') | last)[0:22] }}"

  - debug:
      var: grafana_htpasswd_salt

  - set_fact:
      grafana_secret_contents: "{{ ('supersecret' | password_hash('bcrypt', grafana_htpasswd_salt, ident='2y')) }}"

  - debug:
      var: grafana_secret_contents[29:]
```

**Output**

```bash
$  ansible-playbook -i localhost test.yml
[WARNING]: Unable to parse /home/leif/src/github.com/infrawatch/service-telemetry-operator/localhost as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [k8s test] ************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [localhost]

TASK [Check for existing grafana htpasswd secret] **************************************************************************************************************************
ok: [localhost]

TASK [debug] ***************************************************************************************************************************************************************
ok: [localhost] => {
    "grafana_htpasswd_secret.resources[0].data.auth | b64decode": "root:$2y$12$IijTu/iS92SgPqBDkgU0.OLrilpryAx4b9lDCc6DzeO0nRwDW09LC"
}

TASK [set_fact] ************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ***************************************************************************************************************************************************************
ok: [localhost] => {
    "grafana_htpasswd_salt": "IijTu/iS92SgPqBDkgU0.O"
}

TASK [set_fact] ************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ***************************************************************************************************************************************************************
ok: [localhost] => {
    "grafana_secret_contents[29:]": "LrilpryAx4b9lDCc6DzeO0nRwDW09LC"
}

PLAY RECAP *****************************************************************************************************************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

2023-08-25 18:11 UTC, leifmadsen commented
Latest set of changes. I will remove the debug logs etc from the uploaded PR, but here is the output from logs.

First iteration with no Secret created. This is done with Grafana disabled to start, but secrets are made anyways.

```bash
--------------------------- Ansible Task StdOut -------------------------------

TASK [servicetelemetry : Check for existing grafana htpasswd secret] ***********
task path: /opt/ansible/roles/servicetelemetry/tasks/component_grafana.yml:10

-------------------------------------------------------------------------------
{"level":"info","ts":1692986575.8124166,"logger":"logging_event_handler","msg":"[playbook task start]","name":"default","namespace":"service-telemetry","gvk":"infra.watch/v1beta1, Kind=ServiceTelemetry","event_type":"playbook_on_task_start","job":"5755568030158739278","EventData.Name":"servicetelemetry : Check for existing grafana htpasswd secret"}
{"level":"info","ts":1692986576.657023,"logger":"proxy","msg":"Cache miss: /v1, Kind=Secret, service-telemetry/default-grafana-htpasswd"}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [debug] ******************************** 
ok: [localhost] => {
    "grafana_htpasswd_secret": {
        "changed": false,
        "failed": false,
        "resources": []
    }
}

-------------------------------------------------------------------------------
{"level":"info","ts":1692986576.8599453,"logger":"logging_event_handler","msg":"[playbook debug]","name":"default","namespace":"service-telemetry","gvk":"infra.watch/v1beta1, Kind=ServiceTelemetry","event_type":"runner_on_ok","job":"5755568030158739278","EventData.TaskArgs":""}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [debug] ******************************** 
ok: [localhost] => {
    "msg": "Enter the block"
}

-------------------------------------------------------------------------------
{"level":"info","ts":1692986576.8762813,"logger":"logging_event_handler","msg":"[playbook debug]","name":"default","namespace":"service-telemetry","gvk":"infra.watch/v1beta1, Kind=ServiceTelemetry","event_type":"runner_on_ok","job":"5755568030158739278","EventData.TaskArgs":""}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [Set current Grafana htpasswd salt] ******************************** 
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to be in '/opt/ansible/roles/servicetelemetry/tasks/component_grafana.yml': line 26, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set current Grafana htpasswd salt\n      ^ here\n"}

-------------------------------------------------------------------------------
{"level":"error","ts":1692986577.0040116,"logger":"logging_event_handler","msg":"","name":"default","namespace":"service-telemetry","gvk":"infra.watch/v1beta1, Kind=ServiceTelemetry","event_type":"runner_on_failed","job":"5755568030158739278","EventData.Task":"Set current Grafana htpasswd salt","EventData.TaskArgs":"","EventData.FailedTaskPath":"/opt/ansible/roles/servicetelemetry/tasks/component_grafana.yml:26","error":"[playbook task failed]"}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [debug] ******************************** 
ok: [localhost] => {
    "msg": "Enter rescue"
}

-------------------------------------------------------------------------------
{"level":"info","ts":1692986577.019443,"logger":"logging_event_handler","msg":"[playbook debug]","name":"default","namespace":"service-telemetry","gvk":"infra.watch/v1beta1, Kind=ServiceTelemetry","event_type":"runner_on_ok","job":"5755568030158739278","EventData.TaskArgs":""}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [debug] ******************************** 
ok: [localhost] => {
    "init_grafana_htpasswd_bcrypt_string": "$2y$12$28n2si2pRsfY1Dr0UQOLG.QXZIadRbI5IET.dgndJgKQxdCYTg55C"
}

-------------------------------------------------------------------------------
{"level":"info","ts":1692986577.6068509,"logger":"logging_event_handler","msg":"[playbook debug]","name":"default","namespace":"service-telemetry","gvk":"infra.watch/v1beta1, Kind=ServiceTelemetry","event_type":"runner_on_ok","job":"5755568030158739278","EventData.TaskArgs":""}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [debug] ******************************** 
ok: [localhost] => {
    "grafana_htpasswd_salt": "28n2si2pRsfY1Dr0UQOLG."
}

-------------------------------------------------------------------------------
{"level":"info","ts":1692986577.8788757,"logger":"logging_event_handler","msg":"[playbook debug]","name":"default","namespace":"service-telemetry","gvk":"infra.watch/v1beta1, Kind=ServiceTelemetry","event_type":"runner_on_ok","job":"5755568030158739278","EventData.TaskArgs":""}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [debug] ******************************** 
ok: [localhost] => {
    "msg": "Enter always"
}

-------------------------------------------------------------------------------
{"level":"info","ts":1692986577.8965406,"logger":"logging_event_handler","msg":"[playbook debug]","name":"default","namespace":"service-telemetry","gvk":"infra.watch/v1beta1, Kind=ServiceTelemetry","event_type":"runner_on_ok","job":"5755568030158739278","EventData.TaskArgs":""}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [debug] ******************************** 
ok: [localhost] => {
    "grafana_htpasswd_bcrypt_string": "$2y$12$28n2si2pRsfY1Dr0UQOLG.QXZIadRbI5IET.dgndJgKQxdCYTg55C"
}

-------------------------------------------------------------------------------
{"level":"info","ts":1692986578.5206218,"logger":"logging_event_handler","msg":"[playbook debug]","name":"default","namespace":"service-telemetry","gvk":"infra.watch/v1beta1, Kind=ServiceTelemetry","event_type":"runner_on_ok","job":"5755568030158739278","EventData.TaskArgs":""}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [debug] ******************************** 
ok: [localhost] => {
    "grafana_htpasswd_auth_string": "root:$2y$12$28n2si2pRsfY1Dr0UQOLG.QXZIadRbI5IET.dgndJgKQxdCYTg55C"
}

-------------------------------------------------------------------------------
{"level":"info","ts":1692986578.7997184,"logger":"logging_event_handler","msg":"[playbook debug]","name":"default","namespace":"service-telemetry","gvk":"infra.watch/v1beta1, Kind=ServiceTelemetry","event_type":"runner_on_ok","job":"5755568030158739278","EventData.TaskArgs":""}

--------------------------- Ansible Task StdOut -------------------------------

TASK [servicetelemetry : Create or patch htpasswd secret for grafana admin] ****
task path: /opt/ansible/roles/servicetelemetry/tasks/component_grafana.yml:72

-------------------------------------------------------------------------------
{"level":"info","ts":1692986578.8047097,"logger":"logging_event_handler","msg":"[playbook task start]","name":"default","namespace":"service-telemetry","gvk":"infra.watch/v1beta1, Kind=ServiceTelemetry","event_type":"playbook_on_task_start","job":"5755568030158739278","EventData.Name":"servicetelemetry : Create or patch htpasswd secret for grafana admin"}
{"level":"info","ts":1692986579.6266491,"logger":"proxy","msg":"Cache miss: /v1, Kind=Secret, service-telemetry/default-grafana-htpasswd"}
{"level":"info","ts":1692986579.6300638,"logger":"proxy","msg":"Injecting owner reference"}
{"level":"info","ts":1692986579.6302788,"logger":"proxy","msg":"Watching child resource","kind":"/v1, Kind=Secret","enqueue_kind":"infra.watch/v1beta1, Kind=ServiceTelemetry"}
{"level":"info","ts":1692986579.6303108,"logger":"controller.servicetelemetry-c [...]

2023-08-25 18:26 UTC, csibbitt approved these changes
I heard naming things is hard so I offered some suggestions. Code looks good, though, thank you!

2023-08-25 18:26 UTC, csibbitt commented on roles/servicetelemetry/tasks/component_grafana.yml
> +    - name: Set current Grafana htpasswd salt
s/Set/Read/ or Parse or something showing that it's a read op not a write up

2023-08-25 18:26 UTC, csibbitt commented on roles/servicetelemetry/tasks/component_grafana.yml
> +    - name: Rescue Grafana htpasswd salt
Read newly generated Grafana htpasswd salt

2023-08-25 18:33 UTC, leifmadsen commented
> I heard naming things is hard so I offered some suggestions. Code looks good, though, thank you!

I did another walk through and made these a bit more descriptive. Let me know if you like this.

2023-08-25 18:34 UTC, csibbitt approved these changes

2023-08-25 18:37 UTC, merged